### PR TITLE
zh.yml file updated on 06-11-2012

### PR DESCRIPTION
**Pull request by archonwang**
Simplified Chinese updated 06-11-2012

### CODE REVIEW

**Comment by marutosi** [comment]
I fixed newline.

https://github.com/marutosi/redmine/commit/4a0e63977be6b40995d159289e5c653939523bfa

Please create a issue on Redmine.org and post patch to it.
I created a issue.

http://www.redmine.org/issues/11130

```
$ git log -n1 HEAD | cat
commit 4a0e63977be6b40995d159289e5c653939523bfa
Author: Toshi MARUYAMA <test01@examle.com>
Date:   Mon Jun 11 14:55:04 2012 +0900

    Simplified Chinese


$ git format-patch --stdout HEAD^ > issue-11130.diff
```

Please close this pull request.

**Comment by archonwang** [comment]
Hi，Toshi MARUYAMA

Thanks.

2012-06-11    14:19:33
Steven.W

From: Toshi MARUYAMA
Date: 2012-06-11 14:11
To: Steven.W
Subject: Re: [redmine] zh.yml file updated on 06-11-2012 (#5)
I fixed newline.

https://github.com/marutosi/redmine/commit/4a0e63977be6b40995d159289e5c653939523bfa

Please create a issue on Redmine.org and post patch to it.
I created a issue.

http://www.redmine.org/issues/11130

```
$ git log -n1 HEAD | cat
commit 4a0e63977be6b40995d159289e5c653939523bfa
Author: Toshi MARUYAMA <test01@examle.com>
Date:   Mon Jun 11 14:55:04 2012 +0900

    Simplified Chinese


$ git format-patch --stdout HEAD^ > issue-11130.diff
```

Please close this pull request.

---

**Comment by marutosi** [comment]
Please close this pull request.
I don't have a right to close it.

**Comment by archonwang** [comment]
Thanks a lot.

**Pull request closed without merging**
