### PR TITLE
Updated for Simplified Chinese.

### PR DESCRIPTION
**Pull request by archonwang**
Updated zh.yml file.

### CODE REVIEW

**Comment by marutosi** [comment]
Please create a issue on Redmine and post a patch to it.
http://www.redmine.org/issues/10800

Please close this pull request.
I don't have a right to close pull request.

**Comment by archonwang** [comment]
OK.
thanks.

**Comment by archonwang** [comment]
Hi, marutosi

I'm sorry that I'm not sure how to commit a patch in the redmine website.  :(

**Comment by marutosi** [comment]
See.
- http://www.redmine.org/projects/redmine/wiki/Contribute
- http://www.redmine.org/projects/redmine/wiki/How_to_create_patch_series_on_Mercurial_and_Git

I have already committed this pull request with minor fix.

**Comment by archonwang** [comment]
thanks for your help. I will check it later.

**Pull request closed without merging**
